In [1]:
from scipy.misc import imread

img = imread("DSC00064-740x442.jpg")

C:\Users\egusho\AppData\Local\Continuum\anaconda_3.0\envs\deep\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [42]:
a = np.asarray(img)
a.tofile('foo.csv',sep=',',format='%10.5f')

In [19]:
img.shape

(442, 740, 3)

In [3]:
print(img.flatten())

[93 94 89 ... 10 11 16]


In [13]:
data = img.flatten()

In [38]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [39]:
print(data.reshape(442, 740, 3)) 

#out = csv.writer(open("myfile.csv","w"), delimiter=',',quoting=csv.QUOTE_ALL)
#out.writerow(data.reshape(442, 740, 3))

[[[ 93  94  89]
  [ 90  91  86]
  [ 90  91  85]
  ...
  [ 54  99 166]
  [ 54  99 166]
  [ 54  99 166]]

 [[107 108 103]
  [110 111 105]
  [100 101  95]
  ...
  [ 56 101 168]
  [ 55 100 167]
  [ 55 100 167]]

 [[103 104  98]
  [109 110 104]
  [105 106  98]
  ...
  [ 57 102 169]
  [ 56 101 168]
  [ 56 101 168]]

 ...

 [[160 152 133]
  [159 151 130]
  [158 147 125]
  ...
  [ 12  13  17]
  [ 10  11  15]
  [  8   9  13]]

 [[162 153 136]
  [152 143 126]
  [155 146 129]
  ...
  [ 12  13  18]
  [ 11  12  17]
  [ 10  11  16]]

 [[158 149 132]
  [148 139 122]
  [150 141 124]
  ...
  [ 12  13  18]
  [ 11  12  17]
  [ 10  11  16]]]


In [30]:
import numpy as np
np.save("data.npy", data)

In [31]:
np.load("data.npy")

array([93, 94, 89, ..., 10, 11, 16], dtype=uint8)

In [17]:
lol = [(1,2,3),(4,5,6),(7,8,9)]
item_length = len(data)

with open('test.csv', 'wb') as test_file:
  file_writer = csv.writer(test_file)
  for i in range(item_length):
    file_writer.writerow([x[i] for x in data])

IndexError: invalid index to scalar variable.